let data = [
  {
    id: 0,
    item: "퍼퓸 핸드크림 50ml(4종 택1)",
    company: "체이싱래빗",
    price: "9,900원",
    img: "pro1.png",
  },
  {
    id: 1,
    item: "클래식 핸드크림 100ml(4종 택1)",
    company: "비욘드",
    price: "7,500원",
    img: "pro2.png",
  },
  {
    id: 2,
    item: "타입넘버 핸드크림 40ml 5종(기획)",
    company: "타임넘버",
    price: "10,800원",
    img: "pro3.png",
  },
  {
    id: 3,
    item: "퍼퓸 핸드크림(6종 택1)",
    company: "헉슬리",
    price: "12,000원",
    img: "pro4.png",
  },
  {
    id: 4,
    item: "퍼퓸 핸드크림 50ml 7종",
    company: "W.DRESSROOM",
    price: "5,500원",
    img: "pro5.png",
  },
  {
    id: 5,
    item: "시어버터 드라이 스킨 핸드크림 30ml",
    company: "록시땅",
    price: "17,000원",
    img: "pro6.png",
  },
  {
    id: 6,
    item: "망고씨드버터 퍼퓸 핸드크림 50ml",
    company: "헤트라스",
    price: "8,010원",
    img: "pro7.png",
  },
  {
    id: 7,
    item: "퍼퓸 핸드크림 50ml 6종",
    company: "스카이보틀",
    price: "7,930원",
    img: "pro8.png",
  },
  {
    id: 8,
    item: "퍼퓸키링 핸드크림 50ml 5종 택1",
    company: "멈칫",
    price: "15,110원",
    img: "pro9.png",
  },
  {
    id: 9,
    item: "핸드앤네일 크림 75~100ml 12종 택1",
    company: "카밀",
    price: "3,950원",
    img: "pro10.png",
  },
  {
    id: 10,
    item: "돌체 얼스피그50ml + 베르가못 50ml",
    company: "마르마르디",
    price: "12,900원",
    img: "pro11.png",
  },
  {
    id: 11,
    item: "니치 퍼퓸 핸드크림 50ml 4종 택1",
    company: "더프트앤도프트",
    price: "5,530원",
    img: "pro12.png",
  },
];

export default data;
